### Create a new player
POST http://localhost:8080/api/v1/players
Content-Type: application/json

{
  "player": "John Doe",
  "age": 24,
  "position": "MF",
  "team": "Arsenal",
  "nation": "England",
  "mp": 10,
  "starts": 8,
  "min": 650,
  "gls": 3,
  "ast": 4,
  "pk": 0,
  "crdy": 1,
  "crdr": 0,
  "xg": 2.1,
  "xag": 3.5
}
