### Login Request
###http://10.56.134.17:4000
### http://localhost:4000/
POST http://localhost:4000/authentication/login
Content-Type: application/json

    {
      "email":"test2@gmail.com",
      "password" : "test1234"
    }
###